package xyz.luna.nextcloudextended

import androidx.compose.runtime.compositionLocalOf
import java.util.Locale

/** Supported UI languages. */
enum class AppLanguage { EN, FR }

/**
 * All user-facing strings for one language. Static strings are plain [String]s; strings that embed
 * a runtime value are `(String) -> String` lambdas. Date formatting follows [locale].
 */
class Strings(
    val locale: Locale,
    // Login
    val loginSubtitle: String,
    val serverUrlLabel: String,
    val serverUrlPlaceholder: String,
    val usernameLabel: String,
    val passwordLabel: String,
    val advancedOptions: String,
    val allowInsecureHttp: String,
    val insecureHttpWarning: String,
    val connect: String,
    val languageLabel: String,
    // Tabs / navigation
    val tabCalendar: String,
    val tabTasks: String,
    val tabNotes: String,
    val tabFiles: String,
    val logout: String,
    val loggedOut: String,
    // Common actions
    val add: String,
    val create: String,
    val save: String,
    val cancel: String,
    val rename: String,
    val delete: String,
    val edit: String,
    val open: String,
    val close: String,
    val copy: String,
    val share: String,
    val ok: String,
    val name: String,
    val newName: String,
    val title: String,
    val description: String,
    val location: String,
    val category: String,
    val content: String,
    // FAB content descriptions
    val addTask: String,
    val createNote: String,
    val addEvent: String,
    // Share
    val shareLinkTitle: String,
    val publicLinkCreated: String,
    val linkCopied: String,
    // Event dialogs
    val newEvent: String,
    val editEvent: String,
    val startDateTime: String,
    val endDateTime: String,
    val calendarLabel: String,
    val selectCalendarFirst: String,
    val deleteEventTitle: String,
    val deleteEventConfirm: (String) -> String,
    val recurringEventNotice: String,
    // Drive
    val addToDrive: String,
    val createFolder: String,
    val uploadFile: String,
    val newFolder: String,
    val folderName: String,
    val openWith: String,
    val back: String,
    val driveRoot: String,
    val searchInFolder: String,
    val emptyFolder: String,
    val folder: String,
    val moreOptions: String,
    val sizeMb: String,
    val sizeKb: String,
    val downloadStarted: (String) -> String,
    // Tasks
    val newTask: String,
    val editTaskTitle: String,
    val selectEllipsis: String,
    val createList: String,
    val renameListAction: String,
    val deleteListAction: String,
    val searchTasks: String,
    val noTaskInList: String,
    val noResultsFor: (String) -> String,
    val dueDate: String,
    val dueDatePlaceholder: String,
    val pickDate: String,
    val clearDate: String,
    val newList: String,
    val renameTitle: String,
    val deleteListTitle: String,
    val deleteListConfirm: (String) -> String,
    // Notes
    val newNote: String,
    val editNote: String,
    val searchNotes: String,
    val noNotes: String,
    val defaultCategory: String,
    val noteFallbackLabel: String,
    val favorite: String,
    // Calendar
    val viewDay: String,
    val viewWeek: String,
    val viewMonth: String,
    val viewYear: String,
    val dayInitials: List<String>,
    val hourSuffix: String,
    val noEvent: String,
    val noEventThatDay: String,
    val allDay: String,
    // Validation / errors
    val fillAllFields: String,
    val insecureHttpBlocked: String,
    val fileReadError: (String) -> String,
    val cannotOpen: (String) -> String,
    val connectionFailed: (String) -> String,
    val calendarError: (String) -> String,
    val tasksError: (String) -> String,
    val notesError: (String) -> String,
    val notesNotInstalled: String,
    val filesError: (String) -> String,
    val taskUpdateFailed: (String) -> String,
    val taskCreateFailed: (String) -> String,
    val taskEditFailed: (String) -> String,
    val taskDeleteFailed: (String) -> String,
    val eventDeleteFailed: (String) -> String,
    val eventCreateFailed: (String) -> String,
    val eventEditFailed: (String) -> String,
    val listCreateFailed: (String) -> String,
    val listRenameFailed: (String) -> String,
    val listDeleteFailed: (String) -> String,
    val noteFavFailed: (String) -> String,
    val noteCreateFailed: (String) -> String,
    val noteUpdateFailed: (String) -> String,
    val noteDeleteFailed: (String) -> String,
    val fileDeleteFailed: (String) -> String,
    val fileRenameFailed: (String) -> String,
    val folderCreateError: (String) -> String,
    val uploadFailed: (String) -> String,
    val shareLinkFailed: (String) -> String,
    val downloadFailed: (String) -> String,
    // PDF Viewer
    val loadingPdf: String,
    val pageOf: (Int, Int) -> String,
    val pdfError: String,
    // Settings
    val settings: String,
    val officeViewerSection: String,
    val officeViewerSectionDesc: String,
    val officeViewerPoi: String,
    val officeViewerPoiDesc: String,
    val officeViewerOnline: String,
    val officeViewerOnlineDesc: String,
    val navBarSection: String,
    val navBarSectionDesc: String,
    val navBarHint: String,
    val navBarShownInBar: String,
    val navBarInMoreMenu: String,
    // Office Viewer
    val documentError: String,
    val collaboraLoadFailed: String,
    // Contacts
    val tabContacts: String,
    val createContact: String,
    val newContact: String,
    val editContact: String,
    val phone: String,
    val email: String,
    val organization: String,
    val addPhone: String,
    val addEmail: String,
    val searchContacts: String,
    val noContacts: String,
    val deleteContactTitle: String,
    val deleteContactConfirm: (String) -> String,
    val contactsError: (String) -> String,
    val contactCreateFailed: (String) -> String,
    val contactEditFailed: (String) -> String,
    val contactDeleteFailed: (String) -> String,
    val address: String,
    val street: String,
    val city: String,
    val postalCode: String,
    val country: String,
    val birthday: String,
    val groups: String,
    val group: String,
    val photo: String,
    val addPhoto: String,
    val changePhoto: String,
    val removePhoto: String,
    val addAddress: String,
    val addGroup: String,
    val typeMobile: String,
    val typeHome: String,
    val typeWork: String,
    val typeFax: String,
    val typeOther: String,
)

val EnStrings = Strings(
    locale = Locale.ENGLISH,
    loginSubtitle = "Calendar, Tasks & Notes",
    serverUrlLabel = "Server URL",
    serverUrlPlaceholder = "https://your-nextcloud.com",
    usernameLabel = "Username",
    passwordLabel = "Password",
    advancedOptions = "Advanced options",
    allowInsecureHttp = "Allow insecure HTTP",
    insecureHttpWarning = "Only enable this for a server on a trusted local network. Your credentials will be sent in clear text.",
    connect = "Connect",
    languageLabel = "Language",
    tabCalendar = "Calendar",
    tabTasks = "Tasks",
    tabNotes = "Notes",
    tabFiles = "Drive",
    logout = "Log out",
    loggedOut = "Logged out",
    add = "Add",
    create = "Create",
    save = "Save",
    cancel = "Cancel",
    rename = "Rename",
    delete = "Delete",
    edit = "Edit",
    open = "Open",
    close = "Close",
    copy = "Copy",
    share = "Share",
    ok = "OK",
    name = "Name",
    newName = "New name",
    title = "Title",
    description = "Description",
    location = "Location",
    category = "Category",
    content = "Content",
    addTask = "Add task",
    createNote = "Create note",
    addEvent = "Add event",
    shareLinkTitle = "Share link",
    publicLinkCreated = "Public link created:",
    linkCopied = "Link copied",
    newEvent = "New event",
    editEvent = "Edit event",
    startDateTime = "Start (YYYY-MM-DD HH:MM)",
    endDateTime = "End (YYYY-MM-DD HH:MM)",
    calendarLabel = "Calendar",
    selectCalendarFirst = "Select a calendar first",
    deleteEventTitle = "Delete event?",
    deleteEventConfirm = { "\"$it\" will be permanently deleted." },
    recurringEventNotice = "Recurring event — edit or delete it from the web interface.",
    addToDrive = "Add to Drive",
    createFolder = "Create a folder",
    uploadFile = "Upload a file",
    newFolder = "New folder",
    folderName = "Folder name",
    openWith = "Open with",
    back = "Back",
    driveRoot = "Drive",
    searchInFolder = "Search in this folder...",
    emptyFolder = "Empty folder.",
    folder = "Folder",
    moreOptions = "More options",
    sizeMb = "%.1f MB",
    sizeKb = "%.1f KB",
    downloadStarted = { "Download of $it started" },
    newTask = "New task",
    editTaskTitle = "Edit task",
    selectEllipsis = "Select...",
    createList = "Create a list",
    renameListAction = "Rename list",
    deleteListAction = "Delete list",
    searchTasks = "Search tasks...",
    noTaskInList = "No tasks in this list.",
    noResultsFor = { "No results for \"$it\"" },
    dueDate = "Due date",
    dueDatePlaceholder = "YYYY-MM-DD",
    pickDate = "Pick date",
    clearDate = "Clear date",
    newList = "New list",
    renameTitle = "Rename",
    deleteListTitle = "Delete list?",
    deleteListConfirm = { "Delete '$it' and all its tasks? This cannot be undone." },
    newNote = "New note",
    editNote = "Edit note",
    searchNotes = "Search notes...",
    noNotes = "No notes found.",
    defaultCategory = "General",
    noteFallbackLabel = "NOTE",
    favorite = "Favorite",
    viewDay = "Day",
    viewWeek = "Week",
    viewMonth = "Month",
    viewYear = "Year",
    dayInitials = listOf("M", "T", "W", "T", "F", "S", "S"),
    hourSuffix = ":00",
    noEvent = "No events",
    noEventThatDay = "No events that day",
    allDay = "All day",
    fillAllFields = "Please fill in all fields",
    insecureHttpBlocked = "Insecure HTTP blocked — enable the option in Advanced options.",
    fileReadError = { "File read error: $it" },
    cannotOpen = { "Cannot open: $it" },
    connectionFailed = { "Connection failed: $it" },
    calendarError = { "Calendar error: $it" },
    tasksError = { "Tasks error: $it" },
    notesError = { "Notes error: $it" },
    notesNotInstalled = "The Notes app doesn't seem to be installed on your server. Check that the Notes app is installed and enabled in your Nextcloud apps, then try again.",
    filesError = { "Files error: $it" },
    taskUpdateFailed = { "Task update failed: $it" },
    taskCreateFailed = { "Task creation failed: $it" },
    taskEditFailed = { "Task edit failed: $it" },
    taskDeleteFailed = { "Task deletion failed: $it" },
    eventDeleteFailed = { "Deletion failed: $it" },
    eventCreateFailed = { "Event creation failed: $it" },
    eventEditFailed = { "Event edit failed: $it" },
    listCreateFailed = { "List creation failed: $it" },
    listRenameFailed = { "List rename failed: $it" },
    listDeleteFailed = { "List deletion failed: $it" },
    noteFavFailed = { "Note favorite toggle failed: $it" },
    noteCreateFailed = { "Note creation failed: $it" },
    noteUpdateFailed = { "Note update failed: $it" },
    noteDeleteFailed = { "Note deletion failed: $it" },
    fileDeleteFailed = { "Deletion failed: $it" },
    fileRenameFailed = { "Rename failed: $it" },
    folderCreateError = { "Folder creation error: $it" },
    uploadFailed = { "Upload failed: $it" },
    shareLinkFailed = { "Share link failed: $it" },
    downloadFailed = { "Download failed: $it" },
    loadingPdf = "Loading document…",
    pageOf = { page, total -> "Page $page / $total" },
    pdfError = "Cannot open this PDF",
    settings = "Settings",
    officeViewerSection = "Office Documents",
    officeViewerSectionDesc = "Choose how spreadsheets and documents are opened.",
    officeViewerPoi = "Local viewer (Apache POI)",
    officeViewerPoiDesc = "Renders XLSX, XLS, DOCX and PPTX directly on device — no server required. Basic formatting only.",
    officeViewerOnline = "Collabora / OnlyOffice",
    officeViewerOnlineDesc = "Opens documents in your Nextcloud server's office suite. Requires the Collabora Online or OnlyOffice plugin to be installed.",
    navBarSection = "Navigation bar",
    navBarSectionDesc = "Choose which tabs appear in the main bar.",
    navBarHint = "Select 1 to 4 tabs to pin in the main bar. The others are grouped under the + button.",
    navBarShownInBar = "Shown in the main bar",
    navBarInMoreMenu = "In the + menu",
    documentError = "Cannot open this document",
    collaboraLoadFailed = "Collabora / OnlyOffice is not available on this server",
    tabContacts = "Contacts",
    createContact = "Create contact",
    newContact = "New contact",
    editContact = "Edit contact",
    phone = "Phone",
    email = "Email",
    organization = "Organization",
    addPhone = "Add phone",
    addEmail = "Add email",
    searchContacts = "Search contacts...",
    noContacts = "No contacts found.",
    deleteContactTitle = "Delete contact?",
    deleteContactConfirm = { "\"$it\" will be permanently deleted." },
    contactsError = { "Contacts error: $it" },
    contactCreateFailed = { "Contact creation failed: $it" },
    contactEditFailed = { "Contact edit failed: $it" },
    contactDeleteFailed = { "Contact deletion failed: $it" },
    address = "Address",
    street = "Street",
    city = "City",
    postalCode = "Postal code",
    country = "Country",
    birthday = "Birthday",
    groups = "Groups",
    group = "Group",
    photo = "Photo",
    addPhoto = "Add photo",
    changePhoto = "Change photo",
    removePhoto = "Remove photo",
    addAddress = "Add address",
    addGroup = "Add group",
    typeMobile = "Mobile",
    typeHome = "Home",
    typeWork = "Work",
    typeFax = "Fax",
    typeOther = "Other",
)

val FrStrings = Strings(
    locale = Locale.FRENCH,
    loginSubtitle = "Calendrier, Tâches & Notes",
    serverUrlLabel = "URL du serveur",
    serverUrlPlaceholder = "https://votre-nextcloud.com",
    usernameLabel = "Identifiant",
    passwordLabel = "Mot de passe",
    advancedOptions = "Options avancées",
    allowInsecureHttp = "Autoriser HTTP non sécurisé",
    insecureHttpWarning = "À n'activer que pour un serveur sur réseau local. Vos identifiants circuleront en clair.",
    connect = "Se connecter",
    languageLabel = "Langue",
    tabCalendar = "Agenda",
    tabTasks = "Tâches",
    tabNotes = "Notes",
    tabFiles = "Drive",
    logout = "Se déconnecter",
    loggedOut = "Déconnecté",
    add = "Ajouter",
    create = "Créer",
    save = "Enregistrer",
    cancel = "Annuler",
    rename = "Renommer",
    delete = "Supprimer",
    edit = "Modifier",
    open = "Ouvrir",
    close = "Fermer",
    copy = "Copier",
    share = "Partager",
    ok = "OK",
    name = "Nom",
    newName = "Nouveau nom",
    title = "Titre",
    description = "Description",
    location = "Lieu",
    category = "Catégorie",
    content = "Contenu",
    addTask = "Ajouter tâche",
    createNote = "Créer note",
    addEvent = "Ajouter événement",
    shareLinkTitle = "Lien de partage",
    publicLinkCreated = "Lien public créé :",
    linkCopied = "Lien copié",
    newEvent = "Nouvel événement",
    editEvent = "Modifier l'événement",
    startDateTime = "Début (AAAA-MM-JJ HH:MM)",
    endDateTime = "Fin (AAAA-MM-JJ HH:MM)",
    calendarLabel = "Calendrier",
    selectCalendarFirst = "Sélectionnez un calendrier d'abord",
    deleteEventTitle = "Supprimer l'événement ?",
    deleteEventConfirm = { "« $it » sera supprimé définitivement." },
    recurringEventNotice = "Événement récurrent — modifiez-le ou supprimez-le depuis l'interface web.",
    addToDrive = "Ajouter au Drive",
    createFolder = "Créer un dossier",
    uploadFile = "Importer un fichier",
    newFolder = "Nouveau dossier",
    folderName = "Nom du dossier",
    openWith = "Ouvrir avec",
    back = "Retour",
    driveRoot = "Drive",
    searchInFolder = "Rechercher dans ce dossier...",
    emptyFolder = "Dossier vide.",
    folder = "Dossier",
    moreOptions = "Plus d'options",
    sizeMb = "%.1f Mo",
    sizeKb = "%.1f Ko",
    downloadStarted = { "Téléchargement de $it démarré" },
    newTask = "Nouvelle tâche",
    editTaskTitle = "Modifier la tâche",
    selectEllipsis = "Sélectionnez...",
    createList = "Créer une liste",
    renameListAction = "Renommer la liste",
    deleteListAction = "Supprimer la liste",
    searchTasks = "Rechercher des tâches...",
    noTaskInList = "Aucune tâche dans cette liste.",
    noResultsFor = { "Aucun résultat pour \"$it\"" },
    dueDate = "Échéance",
    dueDatePlaceholder = "AAAA-MM-JJ",
    pickDate = "Choisir date",
    clearDate = "Effacer date",
    newList = "Nouvelle liste",
    renameTitle = "Renommer",
    deleteListTitle = "Supprimer la liste ?",
    deleteListConfirm = { "Supprimer '$it' et toutes ses tâches ? Action irréversible." },
    newNote = "Nouvelle note",
    editNote = "Modifier la note",
    searchNotes = "Rechercher des notes...",
    noNotes = "Aucune note trouvée.",
    defaultCategory = "Général",
    noteFallbackLabel = "NOTE",
    favorite = "Favori",
    viewDay = "Jour",
    viewWeek = "Sem.",
    viewMonth = "Mois",
    viewYear = "Année",
    dayInitials = listOf("L", "M", "M", "J", "V", "S", "D"),
    hourSuffix = "h",
    noEvent = "Aucun événement",
    noEventThatDay = "Aucun événement ce jour",
    allDay = "Toute la journée",
    fillAllFields = "Veuillez remplir tous les champs",
    insecureHttpBlocked = "HTTP non sécurisé bloqué — activez l'option dans Options avancées.",
    fileReadError = { "Erreur lecture fichier : $it" },
    cannotOpen = { "Impossible d'ouvrir : $it" },
    connectionFailed = { "Connexion échouée : $it" },
    calendarError = { "Erreur agenda : $it" },
    tasksError = { "Erreur tâches : $it" },
    notesError = { "Erreur notes : $it" },
    notesNotInstalled = "L'application Notes ne semble pas être installée sur votre serveur. Vérifiez que l'application Notes est installée et activée dans les applications de votre Nextcloud, puis réessayez.",
    filesError = { "Erreur fichiers : $it" },
    taskUpdateFailed = { "Échec mise à jour tâche : $it" },
    taskCreateFailed = { "Création tâche échouée : $it" },
    taskEditFailed = { "Modification tâche échouée : $it" },
    taskDeleteFailed = { "Échec suppression tâche : $it" },
    eventDeleteFailed = { "Suppression échouée : $it" },
    eventCreateFailed = { "Création d'événement échouée : $it" },
    eventEditFailed = { "Modification événement échouée : $it" },
    listCreateFailed = { "Création de liste échouée : $it" },
    listRenameFailed = { "Renommer liste échoué : $it" },
    listDeleteFailed = { "Suppression de liste échouée : $it" },
    noteFavFailed = { "Échec favori note : $it" },
    noteCreateFailed = { "Création note échouée : $it" },
    noteUpdateFailed = { "Mise à jour note échouée : $it" },
    noteDeleteFailed = { "Suppression note échouée : $it" },
    fileDeleteFailed = { "Échec suppression : $it" },
    fileRenameFailed = { "Renommage échoué : $it" },
    folderCreateError = { "Erreur création dossier : $it" },
    uploadFailed = { "Import échoué : $it" },
    shareLinkFailed = { "Lien de partage échoué : $it" },
    downloadFailed = { "Téléchargement échoué : $it" },
    loadingPdf = "Chargement du document…",
    pageOf = { page, total -> "Page $page / $total" },
    pdfError = "Impossible d'ouvrir ce PDF",
    settings = "Paramètres",
    officeViewerSection = "Documents Office",
    officeViewerSectionDesc = "Choisissez comment les tableurs et documents sont ouverts.",
    officeViewerPoi = "Visionneur local (Apache POI)",
    officeViewerPoiDesc = "Ouvre XLSX, XLS, DOCX et PPTX directement sur l'appareil — aucun serveur requis. Mise en forme basique uniquement.",
    officeViewerOnline = "Collabora / OnlyOffice",
    officeViewerOnlineDesc = "Ouvre les documents dans la suite bureautique de votre serveur Nextcloud. Nécessite le plugin Collabora Online ou OnlyOffice.",
    navBarSection = "Barre de navigation",
    navBarSectionDesc = "Choisissez les onglets affichés dans la barre principale.",
    navBarHint = "Sélectionnez 1 à 4 onglets à épingler dans la barre principale. Les autres sont regroupés sous le bouton +.",
    navBarShownInBar = "Affiché dans la barre principale",
    navBarInMoreMenu = "Dans le menu +",
    documentError = "Impossible d'ouvrir ce document",
    collaboraLoadFailed = "Collabora / OnlyOffice n'est pas disponible sur ce serveur",
    tabContacts = "Contacts",
    createContact = "Créer contact",
    newContact = "Nouveau contact",
    editContact = "Modifier le contact",
    phone = "Téléphone",
    email = "E-mail",
    organization = "Organisation",
    addPhone = "Ajouter téléphone",
    addEmail = "Ajouter e-mail",
    searchContacts = "Rechercher des contacts...",
    noContacts = "Aucun contact trouvé.",
    deleteContactTitle = "Supprimer le contact ?",
    deleteContactConfirm = { "« $it » sera supprimé définitivement." },
    contactsError = { "Erreur contacts : $it" },
    contactCreateFailed = { "Création contact échouée : $it" },
    contactEditFailed = { "Modification contact échouée : $it" },
    contactDeleteFailed = { "Suppression contact échouée : $it" },
    address = "Adresse",
    street = "Rue",
    city = "Ville",
    postalCode = "Code postal",
    country = "Pays",
    birthday = "Anniversaire",
    groups = "Groupes",
    group = "Groupe",
    photo = "Photo",
    addPhoto = "Ajouter une photo",
    changePhoto = "Changer la photo",
    removePhoto = "Retirer la photo",
    addAddress = "Ajouter une adresse",
    addGroup = "Ajouter un groupe",
    typeMobile = "Mobile",
    typeHome = "Domicile",
    typeWork = "Travail",
    typeFax = "Fax",
    typeOther = "Autre",
)

fun stringsFor(language: AppLanguage): Strings = when (language) {
    AppLanguage.EN -> EnStrings
    AppLanguage.FR -> FrStrings
}

/** Current UI strings, provided at the app root and switchable at runtime. */
val LocalStrings = compositionLocalOf { EnStrings }
