package xyz.luna.nextcloudextended.account

import java.net.URLDecoder

/** Credentials carried by the "Show QR code for mobile apps" QR of Nextcloud's Security settings. */
data class NextcloudLoginQr(val serverUrl: String, val username: String, val appPassword: String)

/**
 * Parses the login QR code generated by Nextcloud
 * (Settings → Security → Devices & sessions → "Create new app password" → "Show QR code for mobile apps").
 *
 * Format: `nc://login/user:<user>&password:<app password>&server:<https://server>`.
 * Fields may come in any order and values may be URL-encoded. Returns null when the content is
 * not a complete Nextcloud login QR.
 */
fun parseNextcloudLoginQr(raw: String): NextcloudLoginQr? {
    val content = raw.trim()
    val prefix = "nc://login/"
    if (!content.startsWith(prefix, ignoreCase = true)) return null

    val fields = content.substring(prefix.length).split('&').mapNotNull { part ->
        val sep = part.indexOf(':')
        if (sep <= 0) return@mapNotNull null
        val value = runCatching { URLDecoder.decode(part.substring(sep + 1).replace("+", "%2B"), "UTF-8") }
            .getOrNull() ?: return@mapNotNull null
        part.substring(0, sep).lowercase() to value
    }.toMap()

    val server = fields["server"]?.trim().orEmpty()
    val user = fields["user"]?.trim().orEmpty()
    val password = fields["password"].orEmpty()
    if (server.isEmpty() || user.isEmpty() || password.isEmpty()) return null
    return NextcloudLoginQr(normalizeServerUrl(server), user, password)
}
