package xyz.luna.nextcloudextended.ui.theme

import androidx.compose.ui.graphics.Color

// --- Light scheme (seed: #0082C9 Nextcloud blue) ---
val md_light_primary            = Color(0xFF006399)
val md_light_onPrimary          = Color(0xFFFFFFFF)
val md_light_primaryContainer   = Color(0xFFCAE6FF)
val md_light_onPrimaryContainer = Color(0xFF001E30)
val md_light_secondary          = Color(0xFF4E616D)
val md_light_onSecondary        = Color(0xFFFFFFFF)
val md_light_secondaryContainer = Color(0xFFD1E5F3)
val md_light_onSecondaryContainer = Color(0xFF0A1E28)
val md_light_tertiary           = Color(0xFF5A5B7E)
val md_light_onTertiary         = Color(0xFFFFFFFF)
val md_light_tertiaryContainer  = Color(0xFFE1DFFF)
val md_light_onTertiaryContainer = Color(0xFF161537)
val md_light_error              = Color(0xFFBA1A1A)
val md_light_onError            = Color(0xFFFFFFFF)
val md_light_errorContainer     = Color(0xFFFFDAD6)
val md_light_onErrorContainer   = Color(0xFF410002)
val md_light_background         = Color(0xFFF6FAFE)
val md_light_onBackground       = Color(0xFF181C1F)
val md_light_surface            = Color(0xFFF6FAFE)
val md_light_onSurface          = Color(0xFF181C1F)
val md_light_surfaceVariant     = Color(0xFFDCE4EC)
val md_light_onSurfaceVariant   = Color(0xFF40484F)
val md_light_outline            = Color(0xFF70787F)
val md_light_outlineVariant     = Color(0xFFC0C8CF)
val md_light_inverseSurface     = Color(0xFF2D3134)
val md_light_inverseOnSurface   = Color(0xFFEDF1F5)
val md_light_inversePrimary     = Color(0xFF90CCFE)
val md_light_surfaceTint        = Color(0xFF006399)
val md_light_scrim              = Color(0xFF000000)

// --- Dark scheme ---
val md_dark_primary             = Color(0xFF90CCFE)
val md_dark_onPrimary           = Color(0xFF003450)
val md_dark_primaryContainer    = Color(0xFF004B72)
val md_dark_onPrimaryContainer  = Color(0xFFCAE6FF)
val md_dark_secondary           = Color(0xFFB5CAD8)
val md_dark_onSecondary         = Color(0xFF20333E)
val md_dark_secondaryContainer  = Color(0xFF364955)
val md_dark_onSecondaryContainer = Color(0xFFD1E5F3)
val md_dark_tertiary            = Color(0xFFC4C2EB)
val md_dark_onTertiary          = Color(0xFF2C2B4D)
val md_dark_tertiaryContainer   = Color(0xFF424264)
val md_dark_onTertiaryContainer = Color(0xFFE1DFFF)
val md_dark_error               = Color(0xFFFFB4AB)
val md_dark_onError             = Color(0xFF690005)
val md_dark_errorContainer      = Color(0xFF93000A)
val md_dark_onErrorContainer    = Color(0xFFFFDAD6)
val md_dark_background          = Color(0xFF101418)
val md_dark_onBackground        = Color(0xFFE1E3E7)
val md_dark_surface             = Color(0xFF101418)
val md_dark_onSurface           = Color(0xFFE1E3E7)
val md_dark_surfaceVariant      = Color(0xFF40484F)
val md_dark_onSurfaceVariant    = Color(0xFFC0C8CF)
val md_dark_outline             = Color(0xFF8A9299)
val md_dark_outlineVariant      = Color(0xFF40484F)
val md_dark_inverseSurface      = Color(0xFFE1E3E7)
val md_dark_inverseOnSurface    = Color(0xFF2D3134)
val md_dark_inversePrimary      = Color(0xFF006399)
val md_dark_surfaceTint         = Color(0xFF90CCFE)
val md_dark_scrim               = Color(0xFF000000)
