package xyz.luna.nextcloudextended.ui.theme

import androidx.compose.ui.graphics.Color

// --- Light scheme (seed: #0082C9 Nextcloud blue) ---
val md_light_primary            = Color(0xFF0082C9)
val md_light_onPrimary          = Color(0xFFFFFFFF)
val md_light_primaryContainer   = Color(0xFFD3EBF8)
val md_light_onPrimaryContainer = Color(0xFF00334F)
val md_light_secondary          = Color(0xFF5F6B73)
val md_light_onSecondary        = Color(0xFFFFFFFF)
val md_light_secondaryContainer = Color(0xFFDCEFF9)
val md_light_onSecondaryContainer = Color(0xFF00334F)
val md_light_tertiary           = Color(0xFF5A5B7E)
val md_light_onTertiary         = Color(0xFFFFFFFF)
val md_light_tertiaryContainer  = Color(0xFFE1DFFF)
val md_light_onTertiaryContainer = Color(0xFF161537)
val md_light_error              = Color(0xFFBA1A1A)
val md_light_onError            = Color(0xFFFFFFFF)
val md_light_errorContainer     = Color(0xFFFFDAD6)
val md_light_onErrorContainer   = Color(0xFF410002)
val md_light_background         = Color(0xFFFFFFFF)
val md_light_onBackground       = Color(0xFF333333)
val md_light_surface            = Color(0xFFFFFFFF)
val md_light_onSurface          = Color(0xFF333333)
val md_light_surfaceVariant     = Color(0xFFEDEDED)
val md_light_onSurfaceVariant   = Color(0xFF666666)
val md_light_outline            = Color(0xFFBDBDBD)
val md_light_outlineVariant     = Color(0xFFE0E0E0)
val md_light_inverseSurface     = Color(0xFF2D3134)
val md_light_inverseOnSurface   = Color(0xFFEDF1F5)
val md_light_inversePrimary     = Color(0xFF7CC8EE)
val md_light_surfaceTint        = Color(0xFF0082C9)
val md_light_scrim              = Color(0xFF000000)

// --- Dark scheme ---
val md_dark_primary             = Color(0xFF4DB3E6)
val md_dark_onPrimary           = Color(0xFF00334F)
val md_dark_primaryContainer    = Color(0xFF00507A)
val md_dark_onPrimaryContainer  = Color(0xFFCAE6FF)
val md_dark_secondary           = Color(0xFFB5CAD8)
val md_dark_onSecondary         = Color(0xFF20333E)
val md_dark_secondaryContainer  = Color(0xFF364955)
val md_dark_onSecondaryContainer = Color(0xFFD1E5F3)
val md_dark_tertiary            = Color(0xFFC4C2EB)
val md_dark_onTertiary          = Color(0xFF2C2B4D)
val md_dark_tertiaryContainer   = Color(0xFF424264)
val md_dark_onTertiaryContainer = Color(0xFFE1DFFF)
val md_dark_error               = Color(0xFFFFB4AB)
val md_dark_onError             = Color(0xFF690005)
val md_dark_errorContainer      = Color(0xFF93000A)
val md_dark_onErrorContainer    = Color(0xFFFFDAD6)
val md_dark_background          = Color(0xFF121212)
val md_dark_onBackground        = Color(0xFFE1E3E7)
val md_dark_surface             = Color(0xFF121212)
val md_dark_onSurface           = Color(0xFFE1E3E7)
val md_dark_surfaceVariant      = Color(0xFF2C2C2C)
val md_dark_onSurfaceVariant    = Color(0xFFB5B5B5)
val md_dark_outline             = Color(0xFF7A7A7A)
val md_dark_outlineVariant      = Color(0xFF3A3A3A)
val md_dark_inverseSurface      = Color(0xFFE1E3E7)
val md_dark_inverseOnSurface    = Color(0xFF2D3134)
val md_dark_inversePrimary      = Color(0xFF006399)
val md_dark_surfaceTint         = Color(0xFF90CCFE)
val md_dark_scrim               = Color(0xFF000000)

// Surface container tones (navigation bar, bottom sheets, menus) kept neutral like the official client.
val md_light_surfaceContainerLowest = Color(0xFFFFFFFF)
val md_light_surfaceContainerLow    = Color(0xFFF8F8F8)
val md_light_surfaceContainer       = Color(0xFFF3F3F3)
val md_light_surfaceContainerHigh   = Color(0xFFEDEDED)
val md_light_surfaceContainerHighest = Color(0xFFE6E6E6)
val md_dark_surfaceContainerLowest  = Color(0xFF0D0D0D)
val md_dark_surfaceContainerLow     = Color(0xFF1A1A1A)
val md_dark_surfaceContainer        = Color(0xFF1E1E1E)
val md_dark_surfaceContainerHigh    = Color(0xFF282828)
val md_dark_surfaceContainerHighest = Color(0xFF333333)
